<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Seeder;
use App\Models\Rubro;

class RubrosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        Schema::disableForeignKeyConstraints();
        Rubro::truncate();
        Schema::enableForeignKeyConstraints();

        Rubro::insert([
            ['id' => 3, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'ALMACENES NATURISTAS'],
            ['id' => 11, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'ARTICULOS DE BAZAR, MENAJE'],
            ['id' => 12, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'ARTICULOS DE COMUNICACION, INFORMATICA Y ELECTRONICA Y REPARACION'],
            ['id' => 13, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'ARTICULOS DE CUERO Y ARTESANIAS'],
            ['id' => 15, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'ARTICULOS DE ELECTRICIDAD E ILUMINACION'],
            ['id' => 18, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'ASERRADEROS Y/O VENTA DE MADERAS'],
            ['id' => 25, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'CASA DE ARTICULOS DEPORTIVOS'],
            ['id' => 117, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'FABRICACION Y/O VENTA DE HELADOS'],
            ['id' => 62, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'SERVICIO DE GAS ENVASADO Y VENTA DE GAS EN ENVASES DE 10,15,45 KGS Y A GRANEL'],
            ['id' => 63, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'SERVICIO DE VENTA, DISTRIBUCIÓN Y GENERACIÓN DE ENERGIA ELÉCTRICA'],
            ['id' => 88, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'SUPERMERCADOS'],
            ['id' => 96, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'TIENDA DE ROPA Y BOUTIQUES'],
            ['id' => 180, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE ALIMENTOS Y ACCESORIOS DE MASCOTAS   100M2'],
            ['id' => 179, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE ALIMENTOS Y ACCESORIOS DE MASCOTAS  H.100M2'],
            ['id' => 178, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE ALIMENTOS Y ACCESORIOS DE MASCOTAS  H.50M2'],
            ['id' => 124, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE AMBULANTES DE CAFE , TE , POCHOCLOS Y SIMILARES'],
            ['id' => 102, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE APARATOS FOTOGRÁFICOS, SLIDES Y REVELADOS, LABORATARIO FOTOGRÁFICO'],
            ['id' => 153, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE ARTICULOS DE LIMPIEZA AL POR MENOR'],
            ['id' => 17, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE ARTICULOS SANITARIOS'],
            ['id' => 70, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE ARTÍCULOS DE CAMPING , PESCA Y CAZA'],
            ['id' => 103, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE ARTÍCULOS DE RIEGO'],
            ['id' => 101, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE ARTÍCULOS PARA EL HOGAR'],
            ['id' => 106, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE COMIDAS PREPARADAS, ROTISERÍAS, FÁBRICAS DE PASTA'],
            ['id' => 61, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE GAS NATURAL POR RED'],
            ['id' => 80, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE HIERRO, CHAPAS, VENTA DE MADERAS Y MATERIALES PARA CONSTRUCCIÓN EN SECO EN GENERAL'],
            ['id' => 112, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE INSTRUMENTOS Y EQUIPOS DE MUSICA'],
            ['id' => 108, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE LANAS'],
            ['id' => 109, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE LEÑA, CARBÓN Y GAS ENVASADOS'],
            ['id' => 110, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE LIBROS , DIARIOS Y REVISTAS'],
            ['id' => 135, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE MAQUINAS Y HERRAMIENTAS PARA JARDIN'],
            ['id' => 113, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE MATAFUEGOS Y OXIGENO'],
            ['id' => 81, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE NEUMÁTICOS'],
            ['id' => 114, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE REPOSTERIA CASERA, TORTAS, SANDWICHES, JUGOS'],
            ['id' => 9, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE REVESTIMIENTOS DE EXTERIOR (PIEDRAS, LAJAS, ECT)'],
            ['id' => 172, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE REVESTIMIENTOS DE INTERIOR, SANITARIOS Y COCINAS  (H. 100 M2)'],
            ['id' => 137, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE REVESTIMINTOS DE INTERIOR, SANITARIOS Y COCINAS MÁS DE 100 M2'],
            ['id' => 115, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA DE TELAS, CORTINAS, ARTICULOS DE BLANCO, MANTELERIA, TAPICERIA'],
            ['id' => 163, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA MAYORISTA DE FRUTAS Y VERDURAS'],
            ['id' => 146, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA Y RECARGAS DE CERVEZAS (GROWLER)'],
            ['id' => 118, 'rubro_madre' => 'Comercio y Ventas', 'subrubro' => 'VENTA Y/O FABRICAS DE COMESTIBLES REGIONALES (TRUCHAS, QUESOS, ECT)'],
            ['id' => 14, 'rubro_madre' => 'Construcción y Hogar', 'subrubro' => 'FERRETERIAS, PINTURERIAS'],
            ['id' => 0, 'rubro_madre' => 'Educación y Capacitación', 'subrubro' => 'ACADEMIAS, INSTITUTOS DE ENSEÑANZA PARTICULARES'],
            ['id' => 150, 'rubro_madre' => 'Educación y Capacitación', 'subrubro' => 'ESCUELAS DE ESQUI'],
            ['id' => 8, 'rubro_madre' => 'Educación y Capacitación', 'subrubro' => 'JARDINES DE INFANTES, GUARDERIAS'],
            ['id' => 19, 'rubro_madre' => 'Gastronomía', 'subrubro' => 'CAFE CONCERTS, PUBS, CONFITERIAS BAILABLES, CONFITERIAS CON ACTIVIDADES ANEXAS, SNACK BAR'],
            ['id' => 175, 'rubro_madre' => 'Gastronomía', 'subrubro' => 'CAFETERIAS - CAFES     H. 10 MESAS'],
            ['id' => 176, 'rubro_madre' => 'Gastronomía', 'subrubro' => 'CAFETERIAS -CAFES  MÁS DE 10 MESAS'],
            ['id' => 164, 'rubro_madre' => 'Gastronomía', 'subrubro' => 'ELABORACION DE BEBIDAS CON Y SIN ALCOHOL, FABRICA DE CERVEZA CON RESTAURANTE Y/O PIZZERIA'],
            ['id' => 82, 'rubro_madre' => 'Gastronomía', 'subrubro' => 'RESTAURANTES - PARRILLA -PIZZERÍA - CONFITERÍAS SIN ACTIVIDADES ANEXAS'],
            ['id' => 6, 'rubro_madre' => 'Ocio y Entretenimiento', 'subrubro' => 'ALQUILER DE VIDEOS, SERVICIOS DE LOCUTORIOS'],
            ['id' => 119, 'rubro_madre' => 'Ocio y Entretenimiento', 'subrubro' => 'VIDEOS JUEGOS'],
            ['id' => 28, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ADMINISTRACION DE TARJETAS DE CREDITO Y COMPRAS'],
            ['id' => 123, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'AGROVETERINARIA'],
            ['id' => 177, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ALQUILER BAÑOS QUIMICOS, HASTA 3 UNIDADES'],
            ['id' => 156, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ALQUILER DE BAÑOS QUIMICOS'],
            ['id' => 5, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ALQUILER DE HERRAMIENTAS'],
            ['id' => 129, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ALQUILERES DE ESQUI, TRINEOS'],
            ['id' => 155, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'AMBULANCIAS'],
            ['id' => 87, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'AUTOSERVICIOS'],
            ['id' => 20, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'BICICLETERIAS'],
            ['id' => 168, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'BUNGALOWS O CABAÑAS'],
            ['id' => 21, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CABALGATAS'],
            ['id' => 127, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CAMIONES DE CARGAS GENERALES NO COMESTIBLE'],
            ['id' => 22, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CAMPING Y RECREOS NATATORIOS Y BALNEARIOS'],
            ['id' => 23, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CARNICERIAS'],
            ['id' => 24, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CARPINTERIAS'],
            ['id' => 74, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CASA DE TÉ Y AFINES'],
            ['id' => 29, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CASAS DE CREDITOS Y FINANCIERAS'],
            ['id' => 47, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CASINOS'],
            ['id' => 160, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CEMUCO'],
            ['id' => 26, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CERRAJERIAS'],
            ['id' => 143, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CHURRERIA'],
            ['id' => 27, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CIBER'],
            ['id' => 158, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'COCINA DOMICILIARIA'],
            ['id' => 31, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CORRALONES DE MATERIALES'],
            ['id' => 142, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'CRIADERO DE TRUCHAS - CERDOS'],
            ['id' => 169, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'DEPARTAMENTOS'],
            ['id' => 32, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'DEPOSITO DE COMERCIOS'],
            ['id' => 107, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'DESPENSA'],
            ['id' => 34, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'DISQUERIA, RELOJERIAS Y CUCHILLERIAS'],
            ['id' => 162, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'DISTRIBUIDORES MAYORISTAS BEBIDAS ALCOHOLICAS Y NO ALCOHOLICAS'],
            ['id' => 161, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'DISTRIBUIDORES MAYORISTAS DE BEBIDAS ALCOHOLICAS Y NO ALCOHOLICAS'],
            ['id' => 165, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ELABORACION DE BEBIDAS CON Y SIN ALCOHOL, FABRICA DE CERVEZA'],
            ['id' => 126, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'EMPRESAS CONSTRUCTORAS'],
            ['id' => 36, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'EMPRESAS DE RADIO LLAMADAY/TELECOMUNICACIONES, RADIO DE FRECUENCIA MODULADA'],
            ['id' => 35, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'EMPRESAS PRESTATARIAS DE SERVICIO DE CORREO, ENCOMIENDAS,MENSAJERIA'],
            ['id' => 128, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'EMPRESSA DE SALUD PREPAGAS'],
            ['id' => 154, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ENERGIAS RENOVABLES'],
            ['id' => 37, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ESTABLECIMIENTOS ESCOLARES PRIVADOS'],
            ['id' => 171, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ESTACIONES DE SERVICIOS C/ANEXOS'],
            ['id' => 170, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ESTACIONES DE SERVICIOS S/ANEXOS'],
            ['id' => 40, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ESTUDIO JURÍDICOS'],
            ['id' => 38, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ESTUDIOS CONTABLES'],
            ['id' => 39, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ESTUDIOS DE AGRIMENSURA, ARQUITECTURA E INGENIERIA'],
            ['id' => 41, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'FABRICA DE CARTELES'],
            ['id' => 49, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'FIAMBRERÍA'],
            ['id' => 159, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'FOOD TRUCKS'],
            ['id' => 48, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'FORRAJERÍAS'],
            ['id' => 43, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'FÁBRICA DE BLOQUES Y PREMOLDEADOS'],
            ['id' => 44, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'FÁBRICA DE CHOCOLATES'],
            ['id' => 42, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'FÁBRICA DE DULCES CON CONFITERÍA Y REGIONALES'],
            ['id' => 45, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'FÁBRICA DE HIELO'],
            ['id' => 145, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'GALERÍA DE ARTE'],
            ['id' => 58, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'GERIÁTRICOS'],
            ['id' => 50, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'GESTORÍA'],
            ['id' => 166, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'HOTELES'],
            ['id' => 51, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'IMPRENTAS'],
            ['id' => 52, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'IMPRESIONES, FOTOCOPIADOS'],
            ['id' => 53, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'INMOBILIARIAS'],
            ['id' => 55, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'INSTITUCIONES BANCARIAS MIXTAS'],
            ['id' => 54, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'INSTITUCIONES BANCARIAS NACIONALES'],
            ['id' => 67, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'INTRODUCTORES DE MERCADERÍAS SIN DEPÓSITO EN LA LOCALIDAD'],
            ['id' => 68, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'KIOSCOS'],
            ['id' => 95, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'LAVADEROS DE AUTOMÓVILES'],
            ['id' => 69, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'LIBRERÍA Y JUGUETERIA'],
            ['id' => 174, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'LOCAL DE COBRO DE SERVICIOS MÁS DE 2 CAJAS HABILITADAS'],
            ['id' => 173, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'LOCAL DE COBROS DE SERVICIOS  HASTA 2 CAJAS H.'],
            ['id' => 56, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'LUBRICENTROS'],
            ['id' => 57, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'MATADEROS'],
            ['id' => 151, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'MEDIOS DE ELEVACIÓN Y BOLETERÌA'],
            ['id' => 116, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'MERCERIAS Y RETACERIAS'],
            ['id' => 73, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'MUEBLERÍAS Y COLCHONERÍAS'],
            ['id' => 75, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'OPTICAS'],
            ['id' => 130, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ORTOPEDIAS'],
            ['id' => 136, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'OTROS NO CATEGORIZADOS'],
            ['id' => 144, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'PANCHERIA'],
            ['id' => 76, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'PANIFICADOS Y PANADERÍAS'],
            ['id' => 77, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'PELOTEROS, INFLABLES INFANTILES'],
            ['id' => 78, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'PELUQUERIA'],
            ['id' => 59, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'PESCADERÍAS'],
            ['id' => 148, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'PLANTA DE PROCESAMIENTO Y EMPAQUE DE LÚPULO'],
            ['id' => 131, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'POLLERIAS'],
            ['id' => 157, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'PUESTOS EN FERIA REGIONAL'],
            ['id' => 152, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'REFUGIO DE MONTAÑA'],
            ['id' => 60, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'REGALERÍAS'],
            ['id' => 167, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'RESIDENCIALES, HOSTEL,HOSTERIAY MOTELES'],
            ['id' => 141, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SALAS DE ELABORACIÓN DE PRODUCTOS ALIMENTICIOS'],
            ['id' => 79, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SALÓN DE ESTÉTICA PERSONAL, PEDICURAS'],
            ['id' => 140, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SALÓN DE EVENTOS'],
            ['id' => 65, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SERVICIO DE AGUA POTABLE POR RED DOMICILIARIA'],
            ['id' => 84, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SERVICIO DE ASERREO MOVIL'],
            ['id' => 66, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SERVICIO DE COMUNICACIONES Y TELEFONÍA'],
            ['id' => 64, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SERVICIO DE CORREO Y ENCOMIENDAS   -   NACIONALES  - PRIVADOS  Y/O MIXTOS'],
            ['id' => 132, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SERVICIOS DE GRUA (POR UNIDAD)'],
            ['id' => 83, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SERVICIOS DE LAVANDEROS, TINTORERÍAS'],
            ['id' => 134, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SERVICIOS DE SEGURIDAD'],
            ['id' => 85, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SERVICIOS FUNEBRES'],
            ['id' => 86, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SERVIDORES DE INTERNET  / INALAMBRICOS  / CABLE  / FIBRA'],
            ['id' => 139, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'SODERIA'],
            ['id' => 94, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'TALLER DE ALINEACIÓN Y BALANCEO'],
            ['id' => 93, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'TALLER DE CHAPA Y PINTURA'],
            ['id' => 89, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'TALLER DE MOTOSIERRAS Y MAQUINAS DE JARDÍN'],
            ['id' => 92, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'TALLER DE REPARACIÓN DE AUTOS'],
            ['id' => 90, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'TALLER DE REPARACIÓN DE CALZADOS , TALLER DE COSTURA'],
            ['id' => 91, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'TALLERES DE GOMERÍA Y TALLER REPARACIÓN DE BICICLETAS'],
            ['id' => 72, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'TELEVISIÓN POR CIRCUITO CERRADO DE CABLE Y CODIFICADO, EMPRESAS DE TELEVISIÓN SATELITAL'],
            ['id' => 133, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'TERAPIAS ALTERNATIVAS'],
            ['id' => 46, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'VERDULERÍA Y FRUTERÍA'],
            ['id' => 138, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'VIDRIERIA'],
            ['id' => 147, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'VINOTECA'],
            ['id' => 120, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'VIVEROS'],
            ['id' => 121, 'rubro_madre' => 'Otros Servicios', 'subrubro' => 'ZAPATERIA'],
            ['id' => 30, 'rubro_madre' => 'Salud y Bienestar', 'subrubro' => 'CLINICAS, SANATORIOS MEDICOS EN GENERAL, LABORATORIOS DE ANALISIS'],
            ['id' => 111, 'rubro_madre' => 'Salud y Bienestar', 'subrubro' => 'FARMACIAS Y PERFUMERÍAS'],
            ['id' => 10, 'rubro_madre' => 'Salud y Bienestar', 'subrubro' => 'GIMNASIOS'],
            ['id' => 7, 'rubro_madre' => 'Tecnología y Comunicación', 'subrubro' => 'TELEFONIA CELULAR'],
            ['id' => 105, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'AGENCIA DE VENTA BILLETES DE LOTERIA,BINGO, PRODE, QUINIELA Y OTROS JUEGOS DE AZAR'],
            ['id' => 1, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'AGENCIAS DE REMISES'],
            ['id' => 125, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'AGENCIAS DE SEGUROS'],
            ['id' => 2, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'AGENCIAS DE VIAJES Y TURISMO'],
            ['id' => 4, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'ALQUILER DE AUTOMOTORES'],
            ['id' => 97, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'COMPAÑIAS TRANSPORTE DE PASAJEROS DE MEDIA Y LARGA DISTANCIA'],
            ['id' => 33, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'DERECHO DE ACTIVIDADES DE TIPO TURISMO ACTIVO( CANOTAJE,RAFTING,PARAPENTE, VUELOS DE BAUTISMO Y/O VISTAJE DE AVES O TURISMO, TREKKING, MOUNTAIN BIKE'],
            ['id' => 71, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'REMISES, TEXIS, TAXI-FLETES Y TRANSPORTE ESCOLAR'],
            ['id' => 16, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'REPUESTOS DE AUTOMOTORES'],
            ['id' => 149, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'TRANSPORTE DE ARIDOS'],
            ['id' => 99, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'TRANSPORTE DE CARGAS , MUDANZAS Y SIMILARES'],
            ['id' => 100, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'TRANSPORTE DE SUSTANCIAS ALIMENTICIAS'],
            ['id' => 98, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'TRANSPORTE URBANO DE PASAJEROS'],
            ['id' => 104, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'VENTA DE AUTOMOTORES, NUEVOS Y USADOS Y VENTA DE MOTOS DE NUEVAS Y USADAS'],
            ['id' => 122, 'rubro_madre' => 'Transporte y Turismo', 'subrubro' => 'VENTA DE PASAJES DE AUTOTRANSPORTE DE LARGA DISTANCIA'],
        ]);
    }
}
